"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from pathlib import Path
import os


# ================= BASE DIR =================
BASE_DIR = Path(__file__).resolve().parent.parent


# ================= SECURITY =================
SECRET_KEY = 'django-insecure-change-this-key'

DEBUG = True

ALLOWED_HOSTS = []


# ================= INSTALLED APPS =================
INSTALLED_APPS = [

    # DJANGO APPS
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # CUSTOM APP
    'myapp',
]


# ================= MIDDLEWARE =================
MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ================= ROOT URL =================
ROOT_URLCONF = 'myproject.urls'


# ================= TEMPLATES =================
TEMPLATES = [
    {
        'BACKEND':
        'django.template.backends.django.DjangoTemplates',

        # PROJECT LEVEL TEMPLATE FOLDER
        'DIRS': [
            BASE_DIR / 'templates'
        ],

        # APP TEMPLATE SUPPORT
        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ================= WSGI =================
WSGI_APPLICATION = 'myproject.wsgi.application'


# ================= DATABASE =================
DATABASES = {
    'default': {

        'ENGINE':
        'django.db.backends.mysql',

        'NAME':
        'student_db',

        'USER':
        'root',

        'PASSWORD':
        '2006',

        'HOST':
        'localhost',

        'PORT':
        '3306',
    }
}


# ================= PASSWORD VALIDATION =================
AUTH_PASSWORD_VALIDATORS = [

    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },

    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },

    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },

    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ================= LANGUAGE =================
LANGUAGE_CODE = 'en-us'


# ================= TIME ZONE =================
TIME_ZONE = 'Asia/Kolkata'


# ================= INTERNATIONALIZATION =================
USE_I18N = True

USE_TZ = True


# ================= STATIC FILES =================
STATIC_URL = '/static/'


# STATIC FOLDER
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]


# ================= MEDIA FILES =================
MEDIA_URL = '/media/'


MEDIA_ROOT = BASE_DIR / 'media'


# ================= LOGIN SYSTEM =================

# LOGIN PAGE
LOGIN_URL = '/login/'


# AFTER LOGIN REDIRECT
LOGIN_REDIRECT_URL = '/dashboard/'


# AFTER LOGOUT REDIRECT
LOGOUT_REDIRECT_URL = '/login/'


# ================= DEFAULT AUTO FIELD =================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'