# Generated by Django 6.0.5 on 2026-05-16 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_studentprofile_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='photo',
        ),
    ]
