# Generated by Django 6.0.5 on 2026-05-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_studentprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='course_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(blank=True, default='Pending', max_length=100, null=True),
        ),
    ]
