# Generated by Django 6.0.5 on 2026-05-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_studentprofile_paid_fees_studentprofile_pending_fees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(blank=True, default='Pending', max_length=100, null=True),
        ),
    ]
